### PR TITLE
decomposing an md file into small md files & converting md files into one json more in Readme

### PR DESCRIPTION
**Pull request by aviv926**
Added a script for decomposing an md file into small md files and a script for converting md files into one json file.

Additional expansion in the updated README file

### CODE REVIEW

**Comment by nogiszd** [comment]
Hi,
I would like to keep the codebase in one language.
Whenever I will have free time, then I will rewrite these scripts into C# code.

I have near future plan to do whole app rewrite with GUI, so user experience will be easier, and your functionality will have great use there.

**Comment by aviv926** [comment]
> Hi @aviv926,
> I would like to keep the codebase in one language.
> 
> I have near future plan to do whole app rewrite with GUI, so user experience will be easier, and your functionality will have great use there. So whenever I will have free time, then I will rewrite these scripts into C# code.

Excellent thought, thanks for your input. I would recommend that you maybe add a link to my fork so that others can use this method if they want to.

**Comment by nogiszd** [comment]
> Excellent thought, thanks for your input. I would recommend that you maybe add a link to my fork so that others can use this method if they want to.

Sure, I will provide link to your fork. It would be nice if your fork had edited readme with instructions how to use these scripts.

When I will develop new GUI version with your scripts implemented in C#, then you will be mentioned in credits section as original idea giver.

**Comment by aviv926** [comment]
> > Excellent thought, thanks for your input. I would recommend that you maybe add a link to my fork so that others can use this method if they want to.
> 
> Sure, I will provide link to your fork. It would be nice if your fork had edited readme with instructions how to use these scripts.
> 
> When I will develop new GUI version with your scripts implemented in C#, then you will be mentioned in credits section as original idea giver.

for sure The file readme already updated that I prepared the script. It doesn't appear to you?

**Comment by nogiszd** [comment]
Oh, yes. I'm sorry, didn't saw the updated version.

I've already updated mine readme.md with mention to your fork.

**Comment by nogiszd** [comment]
For now I will merge your PR with newly made feature branch.

**Comment by aviv926** [comment]
> @aviv926 For now I will merge your PR with newly made feature branch on which I will develop GUI version.

Long overdue, thanks for this!
And of course for this great project that helped me a lot

**Pull request merged**
